### ISSUE TITLE
Message "Error invoking remote method 'on-file-selected' : Error" 

### ISSUE THREAD

**Issue by tacker66** [arduino/lab-micropython-installer#10]
Message "Error invoking remote method 'on-file-selected' : Error" 
appears when choosing a firmware file manually or when drag-dropping.

**Comment by sebromero** [comment]
Hi @tacker66 
Can you please give me some more information:
- What operating system do you use?
- On which board are you trying to flash MicroPython?
- Which firmware file are you trying to install via drag and drop?
Thanks!

**Comment by tacker66** [comment]
Hi @sebromero 
I am on Win10 and try to flash an Arduino Nano ESP32 with 'firmware.bin' built from https://github.com/micropython/micropython/tree/master/ports/esp32/boards/ARDUINO_NANO_ESP32 on a Linux machine.

**Comment by sebromero** [comment]
Thanks for your quick reply. So to flash that firmware, the board indeed would need to be in native bootloader mode. We'll add that shortly. For now I recommend to use the "standard" way which is to not put the board in bootloader and just click "Install MicroPython".

**Comment by venugudavalli** [comment]
> Thanks for your quick reply. So to flash that firmware, the board indeed would need to be in native bootloader mode. We'll add that shortly. For now I recommend to use the "standard" way which is to not put the board in native bootloader and just click "Install MicroPython". That way it will install the application image (a special build) which should run fine.

Hi sebromero, I am new to Arduino, could you please let me know, how to do it in standard way. Thanks.

**Comment by sebromero** [comment]
Hi @venugudavalli The standard way is to just plug in the board and click on "Install MicroPython". As pointed out in #11 , on Windows you need to first install the drivers for the board.

**Comment by tacker66** [comment]
Hi @sebromero, this now works correctly with v1.2.1. Thx :-)
