### ISSUE TITLE
"No Firmware found" for Portenta c33

### ISSUE THREAD

**Issue by dourosdimitris** [arduino/lab-micropython-installer#16]
https://pasteboard.co/cbC2bzWTCfq6.png

**Comment by sebromero** [comment]
Thank you @dourosdimitris for reporting this! The official PR in the MicroPython repo has not been merged yet: https://github.com/micropython/micropython/pull/11405
Therefore there is no hosted firmware yet. You can however build the firmware from that branch and drag & drop it in the installer tool. Or you just wait a few more days until that PR gets merged :-)

**Comment by dourosdimitris** [comment]
Nice, thanks!
