### ISSUE TITLE
Not able to flash micropython on Arduino nano 33 ble sense Rev2

### ISSUE THREAD

**Issue by saurabh-2905** [arduino/lab-micropython-installer#25]
Hello, I am trying to install Micropython on my Arduino nano, as specified in the title. At first the installer worked great and I was able to run some scripts and play around. Since I am new to this, I was exploring it and tried using different IDEs to see how it works (VSCode, Thonny, Arduino-Lab for Micropython). Everything was working fine. Suddenly, the device froze and I could not upload any files. Later, I was not able to connect to the device. The device was detected, but as soon as I tried to connect to it, it just took ages and did not happen. 

I thought maybe the software is broke and tried to reflash the micropython. I did it directly using the lab-micropython-installer, but it failed. So I thought of doing the whole process again, updating the bootloader, running the Arduino scripts, re-installing the soft-device code, and then flashing Micropython again. But since then it fails every time. In one of the attempt to flash Micropython using this installer, it gave following error:

`Error running bossac: Command failed: "/Applications/MicroPython Installer.app/Contents/Resources/app/node_modules/firmware-flash/bin/darwin/bossac" -d --port=/dev/tty.usbmodem1 -U -i -e -w "/Applications/MicroPython Installer.app/Contents/Resources/app/node_modules/firmware-flash/bin/firmware/SoftDeviceUpdater.bin" -R`

As I said, I am new to this and looking around how to solve this error. Any help would be great. Thanks

Edit:

I tried reinstalling the lab-micropathon-installer and now it gives following error during startup - 

__A JavaScript error occurred in the main process__
`
Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
at createWindow (/private/var/folders/nw/443sknns78l256x46fjj6r0c0000gn/T/AppTranslocation/66A5D8F5-4EC0-4B72-8B96-E8B9E463DAE1/d/MicroPython Installer.app/Contents/Resources/app/main.js:19:11)
at App.<anonymous> (/private/var/folders/nw/443sknns78l256x46fjj6r0c0000gn/T/AppTranslocation/66A5D8F5-4EC0-4B72-8B96-E8B9E463DAE1/d/MicroPython Installer.app/Contents/Resources/app/main.js:55:9)
at App.emit (node:events:513:28)
`

**Comment by sebromero** [comment]
Hi @saurabh-2905 !
Hmm, interesting. `Uncaught Exception: Error: Cannot create BrowserWindow before app is ready at createWindow` this should never happen. I've added another check but I'm not currently able to re-create.

As for the main issue, could you please add the complete log output to this issue? You can obtain it by starting the app from the terminal (see [here](https://github.com/arduino/lab-micropython-installer?tab=readme-ov-file#-reporting-issues);

Open the Terminal app and type: `"/Applications/MicroPython Installer.app/Contents/MacOS/micropython-installer"` then press enter.

**Comment by sebromero** [comment]
If you have any additional info please add it here so I can take a look. Closing this until there is additional data.
